# ===============================
# CONFIGURACI\uFFFDN DE LA APP
# ===============================
spring.application.name=biblioteca-api

# ===============================
# DATOS DE CONEXI\uFFFDN A LA BASE DE DATOS LOCAL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Randyconnigjan15\$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT
# ===============================
jwt.secret=G6RmC8sFJ92nKxPwZ1TqB3yXv7LdH9rTg4M2aQeS5bU8cVwN0pR6tYxF4vB1nLk
jwt.expiration=3600000

# ===============================
# OpenAPI / Swagger
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
