spring.application.name=ms-biblioteca
server.port=9595

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bd_biblioteca_universitaria?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=biblioteca2025BackendJavaFullStackSecureKeyForJWTTokenGeneration
jwt.expiration=3600000
jwt.refresh.expiration=86400000

# Logging Configuration
logging.level.root=INFO
logging.level.pe.edu.idat.msbiblioteca=DEBUG
logging.level.pe.edu.idat.msbiblioteca.security=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# OpenAPI / Swagger settings (Springdoc)
# La UI estará disponible en: /swagger-ui.html o /swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
