spring.application.name=biblioteca

# ================================
#  CONFIGURACIÓN DE BASE DE DATOS
# ================================
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=74842024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================================
#      CONFIG DE HIBERNATE / JPA
# ================================
# Crea o actualiza las tablas automáticamente
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de JWT
jwt.secret=idat2026backendjavafullstackDSFAS6DF78SDA7F89ASDF789ASD7F89ASD7FA89S7FD89ASF7
jwt.expiration=3600000
jwt.refresh.expiration=86400000

# Server
server.port=8080
server.error.include-message=always